# Source configuration for CV dataset ingestion.
# Populate `source_dir` with the path that contains labelled image folders.
# Each entry under `labels` maps a folder or glob to a class label.
source_dir: data/external/cv_source
labels:
  sharp:
    glob: "sharp/**/*"
    label: 1
  blurred:
    glob: "blurred/**/*"
    label: 0
copy_strategy: symlink  # options: copy, symlink
