stages:
  bootstrap-data-dirs:
    cmd: python pipelines/bootstrap_data_dirs.py
    deps:
      - pipelines/bootstrap_data_dirs.py
    outs:
      - data/.bootstrap_complete:
          cache: false
          persist: true
  nlp-preprocess:
    cmd: python pipelines/nlp_prepare_data.py
    deps:
      - pipelines/nlp_prepare_data.py
    outs:
      - data/raw/nlp_sentiment.csv:
          cache: false
          persist: true
      - data/processed/nlp:
          cache: false
          persist: true
  nlp-train:
    cmd: python nlp_service/train.py
    deps:
      - data/processed/nlp/train.csv
      - data/processed/nlp/test.csv
      - nlp_service/train.py
    outs:
      - nlp_service/artifacts/sentiment_model.pkl:
          cache: false
          persist: true
      - nlp_service/artifacts/mlflow_model:
          cache: false
          persist: true
    metrics:
      - nlp_service/artifacts/metrics.json:
          cache: false
  cv-ingest:
    cmd: python pipelines/cv_ingest_data.py
    deps:
      - configs/cv_ingest.yaml
      - pipelines/cv_ingest_data.py
    outs:
      - data/raw/cv:
          cache: false
          persist: true
  cv-preprocess:
    cmd: python pipelines/cv_prepare_data.py
    deps:
      - pipelines/cv_prepare_data.py
      - data/raw/cv
    outs:
      - data/processed/cv/labels.csv:
          cache: false
          persist: true
  cv-train:
    cmd: python cv_service/train.py
    deps:
      - cv_service/train.py
      - data/processed/cv/labels.csv
    outs:
      - cv_service/artifacts/blur_model.joblib:
          cache: false
          persist: true
    metrics:
      - cv_service/artifacts/metrics.json:
          cache: false
  cv-train-cnn:
    cmd: python cv_service/train_cnn.py
    deps:
      - cv_service/train_cnn.py
      - data/processed/cv/labels.csv
    outs:
      - cv_service/artifacts/cnn_model.pt:
          cache: false
          persist: true
    metrics:
      - cv_service/artifacts/cnn_metrics.json:
          cache: false
