apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: easylife
spec:
  replicas: 1
  selector:
    matchLabels: { app: mlflow }
  template:
    metadata:
      labels: { app: mlflow }
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.16.0
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.easylife.svc.cluster.local:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom: { secretKeyRef: { name: minio-creds, key: accesskey } }
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: minio-creds, key: secretkey } }
          args:
            - "mlflow"
            - "server"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "5000"
            - "--backend-store-uri"
            - "sqlite:////mlflow/mlflow.db"
            - "--artifacts-destination"
            - "s3://mlflow"
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
      volumes:
        - name: mlflow-data
          emptyDir: {}
