apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.16.0
        args:
          - mlflow
          - server
          - --host
          - 0.0.0.0
          - --port
          - "5000"
          - --backend-store-uri
          - sqlite:///mlflow.db
          - --artifacts-destination
          - s3://mlflow
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.infra.svc.cluster.local:9000
        - name: AWS_ACCESS_KEY_ID
          value: minio
        - name: AWS_SECRET_ACCESS_KEY
          value: minio123
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow
      volumes:
      - name: mlflow-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: infra
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
